task4.2

diff --git a/.github/workflows/Conditional.yml b/.github/workflows/Conditional.yml
--- a/.github/workflows/Conditional.yml
+++ b/.github/workflows/Conditional.yml
@@ -11,9 +11,27 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       # 1) Step that only runs on main branch
-      - name: Run only on main
-        if: github.ref == 'refs/heads/main'
-        run: echo "This runs only on main branch"
+    #   - name: Run only on main
+    #     if: github.ref == 'refs/heads/main'
+    #     run: echo "This runs only on main branch"
+
+
+      - name: Step that may fail
+        id: risky
+        run: exit 1
+
+      # 2) Step that runs only if previous FAILED
+      - name: Run only if previous failed
+        if: failure()   # or steps.risky.outcome == 'failure'
+        run: echo "Previous step failed!"
+
+#   # 3) Job that runs only on push events (NOT on pull requests)
+#   push-only-job:
+#     : github.event_name == 'push'
+#     runs-on: ubuntu-latest
+#     steps:
+#       - run: echo "This runs only on push events, not PRs"
+
 
     #   # 4) Step with continue-on-error: true
     #   - name: Risky step that may fail
@@ -22,15 +40,3 @@ jobs:
     #     run: |
     #       echo "This step might fail but job continues"
     #       exit 1
-
-    #   # 2) Step that runs only if previous FAILED
-    #   - name: Run only if previous failed
-    #     : failure()   # or steps.risky.outcome == 'failure'
-    #     run: echo "Previous step failed!"
-
-#   # 3) Job that runs only on push events (NOT on pull requests)
-#   push-only-job:
-#     : github.event_name == 'push'
-#     runs-on: ubuntu-latest
-#     steps:
-#       - run: echo "This runs only on push events, not PRs"
