task4.3

diff --git a/.github/workflows/Conditional.yml b/.github/workflows/Conditional.yml
--- a/.github/workflows/Conditional.yml
+++ b/.github/workflows/Conditional.yml
@@ -16,21 +16,21 @@ jobs:
     #     run: echo "This runs only on main branch"
 
 
-      - name: Step that may fail
-        id: risky
-        run: exit 1
+    #   - name: Step that may fail
+    #     id: risky
+    #     run: exit 1
 
-      # 2) Step that runs only if previous FAILED
-      - name: Run only if previous failed
-        if: failure()   # or steps.risky.outcome == 'failure'
-        run: echo "Previous step failed!"
+    #   # 2) Step that runs only if previous FAILED
+    #   - name: Run only if previous failed
+    #     if: failure()   # or steps.risky.outcome == 'failure'
+    #     run: echo "Previous step failed!"
 
-#   # 3) Job that runs only on push events (NOT on pull requests)
-#   push-only-job:
-#     : github.event_name == 'push'
-#     runs-on: ubuntu-latest
-#     steps:
-#       - run: echo "This runs only on push events, not PRs"
+  # 3) Job that runs only on push events (NOT on pull requests)
+  push-only-job:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "This runs only on push events, not PRs"
 
 
     #   # 4) Step with continue-on-error: true
