Update matrix.yml

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -1,47 +1,47 @@
 name: Matrix Python Versions
 
 on:
-  workflow_dispatch: # this allows us to trigger the workflow manually from github UI
+    workflow_dispatch: # this allows us to trigger the workflow manually from github UI
   # push:
   # pull_request:
 
 jobs:
-  python-matrix:
+    python-matrix:
     # name: Python #{{ matrix.python-version }}
     # runs-on: ubuntu-latest
 
-    name: Ubuntu | Python ${{ matrix.python-version }}
-    runs-on: ubuntu-latest
+      name: Ubuntu | Python ${{ matrix.python-version }}
+      runs-on: ubuntu-latest
 
 
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [ "3.10", "3.11", "3.12" ]
-        exclude:
-          - python-version: "3.10"
-            os: windows-latest
+      strategy:
+         fail-fast: false
+        matrix:
+          python-version: [ "3.10", "3.11", "3.12" ]
+          exclude:
+            - python-version: "3.10"
+              os: windows-latest
 
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      steps:
+        - name: Checkout repository
+          uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: actions/setup-python@v5
+          with:
+            python-version: ${{ matrix.python-version }}
 
 
-      - name: Intentionally fail on Python 3.11
-        if: matrix['python-version'] == '3.11'
-        run: |
-          echo "Failing on purpose to demonstrate fail-fast=false"
-          exit 1
+        - name: Intentionally fail on Python 3.11
+          if: matrix['python-version'] == '3.11'
+          run: |
+            echo "Failing on purpose to demonstrate fail-fast=false"
+            exit 1
           
-      - name: Succeed otherwise
-        if: matrix['python-version'] != '3.11'
-        run: echo "This job succeeds."
+        - name: Succeed otherwise
+          if: matrix['python-version'] != '3.11'
+          run: echo "This job succeeds."
 
 
     
